server:
  port: 8082

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.client.RestTemplate: TRACE

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          gluu:
            client-id: f88d166f-034d-4349-9807-f3b09e8e63b0
            client-secret: password
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/gluu
            scope:
              - openid
              - profile
        provider:      
          gluu: 
            issuer-uri: https://gluu.hlgv.net
#            authorization-uri: https://gluu.hlgv.net/oauth2/restv1/authorize
#            token-uri: https://gluu.hlgv.net/oauth2/restv1/token
#            user-info-uri: https://gluu.hlgv.net/oauth2/restv1/userinfo     
#            user-name-attribute: sub
#            jwk-set-uri: https://gluu.hlgv.net/oxauth/restv1/token'