name: OIDC Demo Spring APP CI/CD

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    types: build-image

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build
      run: docker build -t oidc-demoapp-spring .
    - name: Tags
      run: |
        docker tag oidc-demoapp-spring ${{ secrets.DOCKER_HUB_USERNAME }}/oidc-demoapp-spring:${{ github.sha }}
        docker tag oidc-demoapp-spring ${{ secrets.DOCKER_HUB_USERNAME }}/oidc-demoapp-spring:latest
    - name: Push
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/oidc-demoapp-spring:${{ github.sha }}
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/oidc-demoapp-spring:latest
